import type { Metadata } from "next";
import { Inter } from 'next/font/google';

import "./globals.css";
import { cn } from "@/lib/utils";
import { Toaster } from "sonner";
import Providers from "@/components/providers";

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: "Pemulai LanjutJS",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn('text-base antialiased', inter.className)}
      >
        <Providers>
          {children}
        </Providers>
        <Toaster position="top-right" duration={3000} richColors className={inter.className} />
        <div className="isolate"></div>
      </body>
    </html>
  );
}
